/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.MeusServicos.telas;

import br.com.MeusServicos.dal.ModuloConexao;
import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Leandro Clemente
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    public void pontoDeVendas() {
        PontoDeVendas pdv = new PontoDeVendas();
        pdv.setVisible(true);
        PontoDeVendas.lblUsuarioPDV.setText(lblUsuario.getText());
        PontoDeVendas.lblUsuarioPDV.setForeground(Color.red);
        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblVendas = new javax.swing.JLabel();
        lblGastos = new javax.swing.JLabel();
        lblResultadoGastos = new javax.swing.JLabel();
        lblResultadoVendas = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenCad = new javax.swing.JMenu();
        MenCadCli = new javax.swing.JMenuItem();
        MenCadOs = new javax.swing.JMenuItem();
        MenCadUsu = new javax.swing.JMenuItem();
        menServicos = new javax.swing.JMenuItem();
        menCadastroFornecedor = new javax.swing.JMenuItem();
        menEstoque = new javax.swing.JMenu();
        menEstoqueProdutoQuantidade = new javax.swing.JMenuItem();
        menEstoqueInventario = new javax.swing.JMenuItem();
        menCaixa = new javax.swing.JMenu();
        menCaixaCaixa = new javax.swing.JMenuItem();
        menCaixaSuplemento = new javax.swing.JMenuItem();
        menCaixaSangria = new javax.swing.JMenuItem();
        menCompra = new javax.swing.JMenu();
        menCompraCompra = new javax.swing.JMenuItem();
        menContas = new javax.swing.JMenu();
        menContasContas = new javax.swing.JMenuItem();
        menContasClientes = new javax.swing.JMenuItem();
        menPontoDeVendas = new javax.swing.JMenu();
        MenAju = new javax.swing.JMenu();
        MenAjuSob = new javax.swing.JMenuItem();
        MenOpc = new javax.swing.JMenu();
        MenOpcSai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meus Serviços - Controle de Ordens de Serviços");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Administrativo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Data:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Data atual login:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nome do Usuário:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/MeusServicos/icones/Logo_200x164.png"))); // NOI18N

        lblVendas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVendas.setForeground(new java.awt.Color(0, 51, 204));
        lblVendas.setText("Vendas:");

        lblGastos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblGastos.setForeground(new java.awt.Color(255, 0, 0));
        lblGastos.setText(" Gastos:");

        lblResultadoGastos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoGastos.setForeground(new java.awt.Color(255, 0, 0));
        lblResultadoGastos.setText("(R$)");

        lblResultadoVendas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblResultadoVendas.setForeground(new java.awt.Color(0, 51, 204));
        lblResultadoVendas.setText("(R$)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel3)
                    .addComponent(lblData)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultadoVendas))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultadoGastos))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendas)
                    .addComponent(lblResultadoVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGastos)
                    .addComponent(lblResultadoGastos))
                .addGap(80, 80, 80))
        );

        Menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        MenCad.setText("Cadastro");
        MenCad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        MenCadCli.setText("Clientes");
        MenCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadCliActionPerformed(evt);
            }
        });
        MenCad.add(MenCadCli);

        MenCadOs.setText("OS");
        MenCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadOsActionPerformed(evt);
            }
        });
        MenCad.add(MenCadOs);

        MenCadUsu.setText("Usuários");
        MenCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadUsuActionPerformed(evt);
            }
        });
        MenCad.add(MenCadUsu);

        menServicos.setText("Produtos");
        menServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menServicosActionPerformed(evt);
            }
        });
        MenCad.add(menServicos);

        menCadastroFornecedor.setText("Fornecedor");
        menCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastroFornecedorActionPerformed(evt);
            }
        });
        MenCad.add(menCadastroFornecedor);

        Menu.add(MenCad);

        menEstoque.setText("Estoque");
        menEstoque.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        menEstoqueProdutoQuantidade.setText("Produto/Quantidade");
        menEstoqueProdutoQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEstoqueProdutoQuantidadeActionPerformed(evt);
            }
        });
        menEstoque.add(menEstoqueProdutoQuantidade);

        menEstoqueInventario.setText("Inventario");
        menEstoqueInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEstoqueInventarioActionPerformed(evt);
            }
        });
        menEstoque.add(menEstoqueInventario);

        Menu.add(menEstoque);

        menCaixa.setText("Caixa");
        menCaixa.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        menCaixaCaixa.setText("Caixa");
        menCaixaCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCaixaCaixaActionPerformed(evt);
            }
        });
        menCaixa.add(menCaixaCaixa);

        menCaixaSuplemento.setText("Suprimento");
        menCaixaSuplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCaixaSuplementoActionPerformed(evt);
            }
        });
        menCaixa.add(menCaixaSuplemento);

        menCaixaSangria.setText("Sangria");
        menCaixaSangria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCaixaSangriaActionPerformed(evt);
            }
        });
        menCaixa.add(menCaixaSangria);

        Menu.add(menCaixa);

        menCompra.setText("Compra");
        menCompra.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        menCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCompraActionPerformed(evt);
            }
        });

        menCompraCompra.setText("Compra");
        menCompraCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCompraCompraActionPerformed(evt);
            }
        });
        menCompra.add(menCompraCompra);

        Menu.add(menCompra);

        menContas.setText("Contas");
        menContas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        menContasContas.setText("Contas");
        menContasContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menContasContasActionPerformed(evt);
            }
        });
        menContas.add(menContasContas);

        menContasClientes.setText("Clientes");
        menContasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menContasClientesActionPerformed(evt);
            }
        });
        menContas.add(menContasClientes);

        Menu.add(menContas);

        menPontoDeVendas.setText("PDV");
        menPontoDeVendas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        menPontoDeVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menPontoDeVendasMouseClicked(evt);
            }
        });
        menPontoDeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPontoDeVendasActionPerformed(evt);
            }
        });
        Menu.add(menPontoDeVendas);

        MenAju.setText("Ajuda");
        MenAju.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        MenAjuSob.setText("Sobre");
        MenAjuSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSobActionPerformed(evt);
            }
        });
        MenAju.add(MenAjuSob);

        Menu.add(MenAju);

        MenOpc.setText("Opções");
        MenOpc.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        MenOpcSai.setText("Sair");
        MenOpcSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSaiActionPerformed(evt);
            }
        });
        MenOpc.add(MenOpcSai);

        Menu.add(MenOpc);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        setSize(new java.awt.Dimension(1143, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenOpcSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSaiActionPerformed

        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenOpcSaiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //As Linhas abaixo substituem a label lblData pela Data Atual
        Date data = new Date();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(df.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenAjuSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSobActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_MenAjuSobActionPerformed

    private void MenCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadUsuActionPerformed
        CadUsuarios usuario = new CadUsuarios();
        usuario.setVisible(true);
       
    }//GEN-LAST:event_MenCadUsuActionPerformed

    private void MenCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadCliActionPerformed
        CadClientes cliente = new CadClientes();
        cliente.setVisible(true);
        
    }//GEN-LAST:event_MenCadCliActionPerformed

    private void MenCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadOsActionPerformed
        CadOS os = new CadOS();
        os.setVisible(true);
     
    }//GEN-LAST:event_MenCadOsActionPerformed

    private void menServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menServicosActionPerformed
        // TODO add your handling code here:
        CadProduto produto = new CadProduto();
        produto.setVisible(true);
        
    }//GEN-LAST:event_menServicosActionPerformed

    private void menPontoDeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPontoDeVendasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menPontoDeVendasActionPerformed

    private void menPontoDeVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menPontoDeVendasMouseClicked
        // TODO add your handling code here: 
        pontoDeVendas();
    }//GEN-LAST:event_menPontoDeVendasMouseClicked

    private void menCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastroFornecedorActionPerformed
        // TODO add your handling code here:
        CadFornecedor fornecedor = new CadFornecedor();
        fornecedor.setVisible(true);

    }//GEN-LAST:event_menCadastroFornecedorActionPerformed

    private void menEstoqueProdutoQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEstoqueProdutoQuantidadeActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressao deste relatorio?", "Atençao", JOptionPane.YES_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("/reports/Produto_quantidade.jasper"), null, conexao);

                JasperViewer.viewReport(print, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menEstoqueProdutoQuantidadeActionPerformed

    private void menCaixaCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCaixaCaixaActionPerformed
        // TODO add your handling code here:
        telaCaixa caixa = new telaCaixa();
        caixa.setVisible(true);
    }//GEN-LAST:event_menCaixaCaixaActionPerformed

    private void menCaixaSuplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCaixaSuplementoActionPerformed
        // TODO add your handling code here:
        telaSuprimento suplemento = new telaSuprimento();
        suplemento.setVisible(true);
    }//GEN-LAST:event_menCaixaSuplementoActionPerformed

    private void menCaixaSangriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCaixaSangriaActionPerformed
        // TODO add your handling code here:
        telaSangria sangria = new telaSangria();
        sangria.setVisible(true);
    }//GEN-LAST:event_menCaixaSangriaActionPerformed

    private void menEstoqueInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEstoqueInventarioActionPerformed
        // TODO add your handling code here:
        TelaInventario inventario = new TelaInventario();
        inventario.setVisible(true);

    }//GEN-LAST:event_menEstoqueInventarioActionPerformed

    private void menCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCompraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menCompraActionPerformed

    private void menCompraCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCompraCompraActionPerformed
        // TODO add your handling code here:
        TelaCompra compra = new TelaCompra();
        compra.setVisible(true);
    }//GEN-LAST:event_menCompraCompraActionPerformed

    private void menContasContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menContasContasActionPerformed
        // TODO add your handling code here:
        TelaCrediario contas = new TelaCrediario();
        contas.setVisible(true);
    }//GEN-LAST:event_menContasContasActionPerformed

    private void menContasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menContasClientesActionPerformed
        // TODO add your handling code here:
        RelacaoClientes clientes = new RelacaoClientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_menContasClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenAju;
    private javax.swing.JMenuItem MenAjuSob;
    private javax.swing.JMenu MenCad;
    private javax.swing.JMenuItem MenCadCli;
    private javax.swing.JMenuItem MenCadOs;
    public static javax.swing.JMenuItem MenCadUsu;
    private javax.swing.JMenu MenOpc;
    private javax.swing.JMenuItem MenOpcSai;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblGastos;
    private javax.swing.JLabel lblResultadoGastos;
    private javax.swing.JLabel lblResultadoVendas;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVendas;
    private javax.swing.JMenuItem menCadastroFornecedor;
    private javax.swing.JMenu menCaixa;
    private javax.swing.JMenuItem menCaixaCaixa;
    private javax.swing.JMenuItem menCaixaSangria;
    private javax.swing.JMenuItem menCaixaSuplemento;
    private javax.swing.JMenu menCompra;
    private javax.swing.JMenuItem menCompraCompra;
    private javax.swing.JMenu menContas;
    private javax.swing.JMenuItem menContasClientes;
    private javax.swing.JMenuItem menContasContas;
    private javax.swing.JMenu menEstoque;
    private javax.swing.JMenuItem menEstoqueInventario;
    private javax.swing.JMenuItem menEstoqueProdutoQuantidade;
    private javax.swing.JMenu menPontoDeVendas;
    private javax.swing.JMenuItem menServicos;
    // End of variables declaration//GEN-END:variables
}
